# The name that will appear in your GitHub "Actions" tab.
name: Klarity

on:
  schedule:
    - cron: '*/5 * * * *'
  # This line adds a manual "Run workflow" button in the Actions tab.
  # It's great for testing your cron job without waiting 5 minutes.
  workflow_dispatch:

# A workflow is made of one or more "jobs". We only need one.
jobs:
  # We've named our job "run-health-checks".
  run-health-checks:
    # This tells GitHub to use a standard Linux machine for our robot.
    runs-on: ubuntu-latest
    
    # A job is made of one or more "steps". We only need one step.
    steps:
      - name: Call the scheduler endpoint
        # This is the command our robot will execute.
        run: |
          curl --request GET \
          --url '${{ secrets.SCHEDULER_URL }}' \
          --header 'Authorization: Bearer ${{ secrets.CRON_SECRET }}'
